apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rbac.serviceAccountName }}-token
  namespace: xraylab-1
  annotations:
    kubernetes.io/service-account.name: {{ .Values.rbac.serviceAccountName }}
    argocd.argoproj.io/sync-wave: "1"
type: kubernetes.io/service-account-token
