---
- name: Secret injection of validated-patterns
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Run push secrets task
    include_role:
      name: vault_utils
      tasks_from: push_secrets
