{{- range .Values.rbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .bindingName }}
  namespace: {{ .bindingNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .roleRefName }}
subjects:
- kind: {{ .kind | default "ServiceAccount" }}
  name: {{ coalesce .serviceAccountName .userName }}
{{- if .serviceAccountNamespace }}
  namespace: {{ .serviceAccountNamespace }}
{{- end }}
{{- if .apiGroup }}
  apiGroup: {{ .apiGroup }}
{{- end }}
---
{{- end }}
