apiVersion: v1
kind: ConfigMap
metadata:
  name: wait-for-objectstore
  namespace: {{ .Values.global.xraylab.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  wait-for-objectstore.sh: |
    #!/bin/bash
    # Get ODF version
    ODFMINV=$(oc get subs -n openshift-storage odf-operator -o jsonpath='{.status.currentCSV}' | cut -d '.' -f3 )
    if [[ ${ODFMINV} -lt 13 ]]
      then
        oc wait --for=jsonpath='{.status.phase}'=Connected cephobjectstore/ocs-storagecluster-cephobjectstore -n openshift-storage --timeout=100s
      else
        oc wait --for=jsonpath='{.status.phase}'=Ready cephobjectstore/ocs-storagecluster-cephobjectstore -n openshift-storage --timeout=100s
    fi