{{- if .Values.rbac.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: xraylab-1
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-hook: "-15"
{{- end }}

